name: dart_chromecast
version: 1.0.0
description: Pure dart package to cast videos to your ChromeCast device and control their playback
homepage: https://github.com/terrabythia/dart_chromecast

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  universal_io: ^2.0.4
  protobuf: ^2.0.1
  http: ^1.0.0
  cli_util: ^0.4.0
  args: ^2.3.1
  xml: ">=6.1.0 <7.0.0"
  logging: ^1.2.0
  multicast_dns: ^0.3.2+2
